Obscenity.configure do |config|
  config.blacklist   = ["Babaca",
    "BabacÊo",
    "Babacaum",
    "Babacas",
    "B a b a c a s",
    "b a b a c a",
    "b_a_b_a_c_a",
    "b_a_b_a_c_a_s",
    "Bagos",
    "Bago",
    "B a g o",
    "B a g o s",
    "B_a_g_o_s",
    "Br‘_ulio",
    "Br‘_ulho",
    "Braulho",
    "Barraco",
    "Barracos",
    "Bicha",
    "Bixa",
    "Bixinha",
    "Bixona",
    "Bixola",
    "Bichola",
    "Benga",
    "Bichona",
    "B i x a",
    "B i c h a",
    "b_i_x_a",
    "b_i_c_h_a",
    "B i c h o n a",
    "B_i_c_h_o_n_a",
    "Bimbada",
    "Bimbadinha",
    "Bimbadas",
    "Boceta",
    "B o c e t a",
    "B_o_c_e_t_a",
    "B_o_c_e_t_a_s",
    "Bo ce ta",
    "Bocetas",
    "Buceta",
    "Bu ce ta",
    "Bucetas",
    "B u c e t a s",
    "B u c e t a",
    "B_u_c_e_t_a",
    "B_u_c_e_t_a_s",
    "Boga",
    "Bogas",
    "Boiola",
    "Boiolas",
    "B o i o l a",
    "B o i o l a s",
    "B_o_i_o_l_a_s",
    "B_o_i_o_l_a",
    "B_o_l_a",
    "B_o_l_a_s",
    "B o l a s",
    "Boquete",
    "Boquetes",
    "BoquetÍ_o",
    "Boquetaum",
    "B o q u e t e",
    "B o q u e t e s",
    "B_o_q_u_e_t_e",
    "B_o_q_u_e_t_e_s",
    "Boquetera",
    "Boqueteira",
    "Boquetero",
    "Boqueteiro",
    "B o q u e t e i r a",
    "B o q u e t e i r o",
    "B o s t a",
    "B o s t a s",
    "B_o_s_t_a",
    "B_o_s_t_a_s",
    "Brocha",
    "Bronha",
    "Bronhas",
    "B r o n h a s",
    "B r o n h a",
    "B_r_o_n_h_a",
    "B_r_o_n_h_a_s",
    "Broxar",
    "Broxas",
    "Broxa",
    "Broxar",
    "Broxinha",
    "BroxÍ_o",
    "Brocha",
    "B r o x a",
    "B r o x a s",
    "B_r_o_x_a",
    "B_r_o_x_a_s",
    "B u n d a",
    "B u n d a s",
    "B_u_n_d_a",
    "B_u_n_d_a_s",
    "BundÍ_o",
    "Bundaum",
    "Caba_„o",
    "C a b a _„ o",
    "C_a_b_a__„_o",
    "Ca ba _„o",
    "caba _„o",
    "ca ba_„o",
    "Caba_„Í_o",
    "CabassÍ_o",
    "Cabasso",
    "CabrÍ_o",
    "Cabrona",
    "Caceta",
    "C a c e t e",
	"Cacete",
    "C a c e t e s",
	"Cacetes",
    "C_a_c_e_t_e",
    "CacetÍ_o",
    "Cacetinho",
    "Cacetudo",
    "Cacetuda",
    "Cu de rola",
    "CafetÍ_o",
    "Caguei",
    "C_a_g_a_r",
    "Cagan_„a",
    "Cagativo",
    "Calhorda",
    "Carcamano",
    "Caralho",
    "Cara_„as",
    "Coraca",
    "Casseta",
    "Cassetudo",
    "CassetÍ_o",
    "Cassetaum",
    "C h i f r e",
    "C_h_i_f_r_e",
    "ChifrÍ_o",
    "Choto",
    "Chupisco",
    "Chupisca",
    "C h u p a d a",
    "C h u p a d a s",
    "C_h_u_p_a_d_a",
    "Chibil",
    "Chibiu",
    "Chibio",
    "Chupa Rola",
    "Chuparola",
    "Chupa_rola",
    "ChupÍ_o",
    "Chupaum",
    "Chuparinho",
    "Koko",
    "Kok_„ñ",
    "CocozÍ_o",
    "Coc_„ñ",
    "CocozÍ_o",
    "Coiso",
    "Coisar",
    "ColhÍ_o",
    "Colhudo",
    "ColhÍ_es",
    "C o m e",
    "C o m e r",
    "Cona",
    "C o r n o",
    "C_o_r_n_o_s",
    "Cr‘_pula",
    "Cricri",
    "Cripentolha",
    "Cus",
    "C u",
    "C_u",
    "C_u_s",
    "Ku",
    "K_u",
    "K H no muro",
    "KH",
    "KHR",
    "Curra",
    "Currar",
    "Currada",
    "CuzÍ_o",
    "Cuzao",
    "Cuzaum",
    "C_u_z_Í__o",
    "C_u_z_a_o",
    "D a r",
    "D_a_r",
    "Deflorar",
    "Desflorar",
    "Descaba_„ar",
    "Descaba_„o",
    "Desgra_„a",
    "Enchedor de saco",
    "Encrenca",
    "Enrabar",
    "Enrabada",
    "Enrabado",
    "Entesar",
    "Escrota",
    "Escroto",
    "E s c r o t o",
    "E_s_c_r_o_t_o",
    "EscrotÍ_o",
    "Escrotinho",
    "Estuprador de",
    "Estupradora",
    "Estupro",
    "Filha da Puta",
    "Filho_da_puta",
    "Filhadaputa",
    "Filho da puta",
    "Filhodaputa",
    "Filhodeumaputa",
    "Filhadeumaputa",
    "Filha de uma putanheiro",
    "Filho de uma puta",
    "Filho de um arronque",
    "Filho de um marronque",
    "Fiof‘¢",
    "Fiofoh",
    "Phiopho",
    "F i o f o",
    "Fiofo",
    "Fiof_„ñ",
    "FiofÍ_o",
    "Fiofinho",
    "Foda",
    "F o d a",
    "F_o_d_a",
    "FodÍ_o",
    "Foda-se!",
    "Fodedor",
    "Fudedor",
    "Fuck",
    "Fodedor",
    "Foder",
    "Fuder",
    "F_u_d_e_r",
    "F o d e r",
    "F_o_d_e_r",
    "Foder-se",
    "Se foder",
    "Se fuder",
    "Fodido",
    "F r e s c o",
    "F_r_e_s_c_o",
    "FrescÍ_o",
    "G_a_l_i_n_h_a",
    "G a l i n h a",
    "GaranhÍ_o",
    "Gilete",
    "Gloques",
    "Grelo",
    "Jeba",
    "J e b a",
    "M a m i l o",
    "M_a_m_i_l_o",
    "MamilÍ_o",
    "Mamilao",
    "Mamilaum",
    "MachÍ_o",
    "Machona",
    "Machorra",
    "Maxorra",
    "Maxoha",
    "M a c h o r r a",
    "Machuda",
    "Man_„_",
    "ManezÍ_o",
    "Manzapo",
    "Mars‘_pio",
    "Marmita",
    "Marica",
    "Mariquinha",
    "Marikinha",
    "Maricon",
    "M a r i c a",
    "M_a_r_i_c_a",
    "Maricas",
    "M e r d a",
    "M_e_r_d_a",
    "Merdinha",
    "Merda",
    "Merdoso",
    "Mete",
    "M i j o",
    "M_i_j_o",
    "MijÍ_o",
    "Mijentinho",
    "Mijento",
    "Minette",
    "Nhanha",
    "Obrar",
    "Ovo",
    "O v o",
    "PajoÍ_o",
    "PaijoÍ_o",
    "Panasca",
    "Panaca",
    "Paquete",
    "P a u",
    "P_a_u",
    "Pal",
    "P a l",
    "P_a_l",
    "Pau-no-cu",
    "Paunocu",
    "Pau no cu",
    "Pau_no_cu",
    "Pau no ku",
    "Pecunhaba",
    "Ped_",
    "Peitola",
    "P e i t o",
    "P e i t o s",
    "PeitÍ_o",
    "Pela Saco",
    "Pela_saco",
    "Pelasaco",
    "Peripat_„_tica",
    "Peripat_„_tico",
    "Pentelheira",
    "P e n t e l h o",
    "P_e_n_t_e_l_h_o",
    "Peroba",
    "Pica",
    "P i c a",
    "Pi ca",
    "Pika",
    "Pik",
    "P i k",
    "Pi k",
    "P ik",
    "P ica",
    "Pic a",
    "P_ica",
    "Pic_a",
    "P_i_c_a",
    "Pi_„a",
    "P i _„ a",
    "P_i__„_a",
    "Pi _„a",
    "Pi_„a balÍ_o",
    "pissa",
    "picha",
    "Piriquita",
    "Piroca",
    "P i r o c a",
    "PirocÍ£o",
    "Pirocaum",
    "Pirocao",
    "P i r o c a",
    "Pirocudo",
    "Pirocuda",
    "Pogobol mental",
    "Porra",
    "Porrinha",
    "PorrÍ_o",
    "P o r r a",
    "P_o_r_r_a",
    "Poha",
    "P o h a",
    "Purra",
    "P_„ñrra",
    "Pora",
    "Porra louca",
    "Priquita",
    "Priquito",
    "Punheta",
    "Punhetinha",
    "Punhetudo",
    "P u n h e t a",
    "P_u_n_h_e_t_a",
    "Punheteira",
    "Punheteiro",
    "Puta",
    "P u t a",
    "P_u_t_a",
    "Pu ta",
    "Put a",
    "Putinha",
    "Putona",
    "Puto",
    "PutÍ£o",
    "Putaum",
    "Putao",
    "Putamerda",
    "Puta merda",
    "Putanheiro",
    "Puta que o pariu",
    "Puta_que_pariu",
    "P_u_t_a_q_u_e_p_a_r_i_u",
    "Puta_que_pariu",
    "Puta_que_pario",
    "Puta que pariu",
    "Puta que pario",
    "Puta que o pario",
    "Putaquepariu",
    "Putaquepario",
    "Putaqueopariu",
    "Putaqueopario",
    "Puteiro",
    "P u t e i r o",
    "PutzGrila",
    "Putz Grila",
    "Puts Grila",
    "PutsGrila",
    "Quenga",
    "Kenga",
    "Rabo",
    "Rabeta",
    "R a b o",
    "R_a_b_o",
    "Rameira",
    "Rola",
    "R_„ñla",
    "R o l a",
    "Rosca",
    "R_o_s_c_a",
    "Rosca Frouxa",
    "Roscafrouxa",
    "Roscafroucha",
    "Rosca Froxa",
    "Rosca Frocha",
    "Rosca Froucha",
    "Rosca_Froucha",
    "Rosca_Froxa",
    "Rosca_Frouxa",
    "Rosqueirada",
    "Saqueta",
    "Sacanear",
    "Sacote",
    "SacÍ£o",
    "Sacudo",
    "Saqueira",
    "S_a_c_o",
    "S a c o",
    "S a f a d o",
    "S a f a d a",
    "Safadinha",
    "SafadÍ£o",
    "Safadinho",
    "Sangalho",
    "SapatÍ£o",
    "Sapatinha",
    "Siririca",
    "S i r i r i c a",
    "S_i_r_i_r_i_c_a",
    "Suruba",
    "Sirigaita",
    "sexo",
    "S e x o",
    "Secso",
    "Sekso",
    "Sesso",
    "Secho",
    "Cexo",
    "Cecso",
    "S_e_x_o",
    "Sexo selvagem",
    "Tabacudo",
    "T a r a d o",
    "TaradÍ_o",
    "Taradinha",
    "Taradinho",
    "Tarraqueta",
    "TesÍ_o",
    "Tta",
    "T t a",
    "T e t a",
    "T_e_t_a",
    "TetÍ_o",
    "Toba",
    "Tobaco",
    "T r a n s a r",
    "T r a n s a",
    "Traveco",
    "Transinha",
    "Trepada",
    "Trepadinha",
    "Trepar",
    "Tric_„ñ e croch_",
    "Trottoir",
    "Vaca",
    "V_a_g_i_n_a",
    "V a g i n a",
    "VaginÍ_o",
    "Vagininha",
    "V_a_c_a",
    "Vaivem",
    "Vai vem",
    "Veado",
    "Viado",
    "V_e_a_d_o",
    "V_i_a_d_o",
    "Xana",
    "X_a_n_a",
    "X a n a",
    "Xaninha",
    "Xanosa",
    "Xavasca",
    "Xereca",
    "Xeca",
    "X e c a",
    "X_e_c_a",
    "Xereca",
    "Shereca",
    "Chereca",
    "Xerequinha",
    "Xexeca",
    "Xoxolteiro",
    "Xota",
    "X o t a",
    "X_o_t_a",
    "Xo ta",
    "Xot a",
    "Xoxota",
    "X o x o t a",
    "Xoxotinha",
    "X o x o t i n h a",
    "Xoxotona",
    "X o x o t o n a",
    "Xoxoteira",
    "X o x o t e i r a",
    "Xoxoteiro",
    "X o x o t e i r o",
    "a r a n h a",
    "traidora",
    "t r a i d o r a",
    "Falsa",
    "inìtil",
    "idiota",
    "piranha",
    "p i r a n h a",
    "vagabunda",
    "v a g a b u n d a",
    "retardada",
    "r e t a r d a d a",
    "boticˆrio lixo",
    "traidora",
    "sapata",
    "s a p a t a",
    "sapatÜo",
    "preto sujo",
    "nego",
    "machorra",
    "m a c h o r r a",
    "machorrão",
    "m a c h o r r ã o",
    "bunda",
    "b u n d a",
    "fdp",
    "gordo",
    "gorda",
    "g o r d a",
    "g o r d o",
    "f d p",
    "pnc",
    "p n c",
    "feminazi"]
end
